### ISSUE TITLE
Command gives the wrong date

### ISSUE THREAD

**Issue by oyhel** [tiuub/DateHotkey#1]
Thank you for this tool, very useful for those dealing with dates and booking in the future.

I have a problem in that:
`#today+4days`
outputs 11/09/2025 (todays date is 7th of Sept 2021). I am not sure why this does not work. I should note I am from a country where the date is on the format day/month/year, but from reading the code this should be picked up automatically?

**Comment by tiuub** [comment]
Hello @oyhel,

so I'm living in a country with the format DD.MM.YYYY. This might be an issue due to the string conversion of the formats.

Your kind of lucky, because I'm very busy right now and wouldn't be able to handle this until October, but due to AutoHotkeys light transition in using only plain text files, I'm able to check this in the train. I will notify you, if I find something.

Another side note. You can shorten your entered hotstring. The '+' in the hosting is only a proof of concept, you are able to use it, but it isn't necessary and can be left empty. Nevertheless, the other way around you have to use the '-'. The 'days' can also be shortened to 'd'. This also works with weeks ('w'), months ('m') and years ('y').

So you should end up with `#today4d`


Kind regards
tiuub

**Comment by oyhel** [comment]
Thank you for the quick response and the tips `#today4d` gives me the expected result. 

I played around a bit and I think I know that the problem is. When writing `#today+4days` it jumps 4 years and 4 days, so I think the 'd' and 'y' in days is being picked up. Could this be a bug in the parsing of 'days'?

**Comment by tiuub** [comment]
Hi @oyhel,

I tried to reproduce your issue, but I'm not able to get it. When I'm entering the command with my time format, it just works well. 

So for better understanding, can you tell me your country, your time region and the language you which you are using on your computer?

Kind regards
tiuub

**Comment by oyhel** [comment]
Hi @tiuub,
I am from Norway (time zone is UTC+1 Europe/Oslo). Using Win10 English (US) with Norwegian keyboard (and layout). I have tried changing keyboard layouts to see if that had any effect, but same problem unfortunately.

Thanks again!

**Comment by tiuub** [comment]
Hi @oyhel,

I fixed it in the late evening yesterday. Just give it a try and leave some feedback, if you want.

Kind regards
tiuub

**Comment by oyhel** [comment]
Fantastic, works like a charm! Oh, btw, there is a MsgBox popping up (with message 0) right before the conversion to the data, remains from testing perhaps? ;) Anyways, thanks again for quickly looking into this!

**Comment by tiuub** [comment]
Oh no. This is left from debugging. I will remove this and release a new update.

Kind regards
tiuub
